services:

  server:
    build: ./server
    container_name: web-lab-server
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: web-lab-client
    ports:
      - "80:80"
    depends_on:
      - server
