services:
  mongodb:
    image: mongo:7
    container_name: badhon-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: web-lab-server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/badhon
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: web-lab-client
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  mongo_data:
