name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run test/JSONPlaceholder_API_50_Request_Test_Suite.postman_collection.json

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/web-lab
            git pull origin development
            docker compose down --remove-orphans
            docker compose up -d --build
